version: "3.8"

x-common-setup: &common-setup
  build:
    context: ..
    dockerfile: Dockerfile
  privileged: true
  network_mode: mxck0021-net
  volumes:
    - /home/mxck/mxck2_ws:/mxck2_ws
    - /dev:/dev
  stdin_open: true

services:
  control:
    <<: *common-setup
    container_name: mxck2_control
    command: bash

  foxglove:
    <<: *common-setup
    container_name: mxck2_foxglove
    ports:
      - "8765:8765"
    command: bash -i -c "run_foxglove"

  camera:
    <<: *common-setup
    container_name: mxck2_camera
    command: bash -i -c "run_camera"

  micro:
    <<: *common-setup
    container_name: mxck2_micro
    command: bash -i -c "run_micro"

  kickstart:
    <<: *common-setup
    container_name: mxck2_kickstart
    command: bash -i -c "kickstart"

  lidar:
    <<: *common-setup
    container_name: mxck2_lidar
    command: bash -i -c "run_lidar"
