version: "3.8"

x-common-setup: &common-setup
  build:
    context: ..
    dockerfile: Dockerfile
  privileged: true
  network_mode: mxck0021-net
  volumes:
    - /home/mxck/mxck2_ws:/mxck2_ws
    - /dev:/dev
  stdin_open: true

services:
  control:
    <<: *common-setup
    container_name: mxck2_control
    command: bash